# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 647a3b80ec6b769c71286a60317d1dfbec7fc42c2be8068c60b7918f19c71e2be8df7e9ae0ae6e7bf911aaf3916aecbc2c7c28d88b69bb7e2f7de450352d8458

test:
  secret_key_base: fe00bc6666eb945cb79707dd47b3e0dc4f1d665d2a089cbca0b5794d7d067dc9a8f408747a0883e6664cee01a3d69feec793087467bcc5eddefdf48e2a3b2972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
